# Generated by Django 6.1.1 on 2026-09-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('queue_date', models.DateField()),
                ('current_number', models.PositiveIntegerField(default=0)),
                ('service_point', models.ForeignKey(limit_choices_to={'node_type': 'SERVICE_POINT'}, on_delete=django.db.models.deletion.CASCADE, related_name='queues', to='facility.node')),
            ],
            options={
                'unique_together': {('service_point', 'queue_date')},
            },
        ),
        migrations.CreateModel(
            name='QueueTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('WAITING', 'Waiting'), ('CALLED', 'Called'), ('SERVING', 'Serving'), ('DONE', 'Done'), ('SKIPPED', 'Skipped')], default='WAITING', max_length=20)),
                ('called_at', models.DateTimeField(blank=True, null=True)),
                ('queue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='queues.queue')),
                ('visit_step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='queue_ticket', to='visits.visitstep')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, 'Mon'), (1, 'Tue'), (2, 'Wed'), (3, 'Thu'), (4, 'Fri'), (5, 'Sat'), (6, 'Sun')])),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('service_point', models.ForeignKey(limit_choices_to={'node_type': 'SERVICE_POINT'}, on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='facility.node')),
            ],
        ),
    ]
