# Generated by Django 6.1.1 on 2026-09-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
        ('pathway', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hn_code', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField()),
                ('national_id', models.CharField(blank=True, max_length=13)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('preferred_language', models.CharField(choices=[('th', 'ไทย'), ('en', 'English')], default='th', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('REGISTERED', 'Registered'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('qr_token', models.CharField(max_length=64, unique=True)),
                ('uses_wheelchair', models.BooleanField(default=False)),
                ('current_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits_here', to='facility.node')),
                ('pathway_template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='pathway.pathwaytemplate')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='visits', to='visits.patient')),
            ],
        ),
        migrations.CreateModel(
            name='VisitStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('IN_PROGRESS', 'In Progress'), ('DONE', 'Done'), ('SKIPPED', 'Skipped')], default='PENDING', max_length=20)),
                ('is_planned', models.BooleanField(default=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('prerequisite_steps', models.ManyToManyField(blank=True, related_name='dependent_steps', to='visits.visitstep')),
                ('service_point', models.ForeignKey(limit_choices_to={'node_type': 'SERVICE_POINT'}, on_delete=django.db.models.deletion.PROTECT, related_name='visit_steps', to='facility.node')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='visits.visit')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
