# Generated by Django 6.1.1 on 2026-09-19 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitstep',
            name='is_next',
            field=models.BooleanField(default=False),
        ),
    ]
