# Generated by Django 6.1.1 on 2026-09-19 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0003_backfill_is_next'),
    ]

    operations = [
        migrations.AddField(
            model_name='visit',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text="Set once the visit transitions to COMPLETED (see visits.services.sync_visit_completion). Used for Executive Reports' average total-hospital-time metric.", null=True),
        ),
    ]
