"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-90sk^6l1h+xf1t14c93x*iuekzg8u-+eh5jesdo7bii&p5avtu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'khal.tortoise-theropod.ts.net']

# Next.js rewrites (used to serve the API from the same origin as the
# frontend) drop the trailing slash from wildcard path segments, so API
# routes are defined without one and Django must not redirect to add it.
APPEND_SLASH = False


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'corsheaders',
    'core',
    'facility',
    'pathway',
    'visits',
    'queues',
    'accounts',
]

AUTH_USER_MODEL = 'accounts.StaffUser'

# No per-role enforcement yet (see IMPLEMENT_PLAN.md Phase 0 decision log) —
# accounts/views.py wires up real session login so the Admin Portal knows
# the signed-in StaffUser's actual role, but every endpoint stays AllowAny
# until a future phase adds role-based permission classes.
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Hospital Wayfinding API',
    'DESCRIPTION': (
        "Backend API for the hospital wayfinding platform. Drives the "
        "Admin Portal (master data, queue console, reports), the Patient "
        "Portal (tokenless visit tracking via a per-visit `qr_token`), and "
        "the Kiosk Portal (Phase 4).\n\n"
        "All endpoints are currently `AllowAny` — real session login is wired "
        "but role-based permission classes land in a later phase."
    ),
    'VERSION': '0.1.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'CONTACT': {
        'name': 'Hackathon team',
        'url': 'https://github.com/anomalyco/opencode',
    },
    'LICENSE': {
        'name': 'Internal — hackathon project',
    },
    'SERVERS': [
        {'url': 'http://localhost:8000', 'description': 'Local development (Django runserver)'},
        {'url': 'http://localhost:3000/api', 'description': 'Through the Next.js dev proxy'},
    ],
    'TAGS': [
        {'name': 'accounts', 'description': 'Staff user authentication, master data, and audit log.'},
        {'name': 'facility', 'description': 'Hospital map master data — buildings, floors, nodes (rooms/service points/kiosks), and graph edges between them.'},
        {'name': 'pathway', 'description': 'Care pathways — reusable templates of ordered service-point steps that visits are instantiated from.'},
        {'name': 'queues', 'description': 'Per-day queues per service point, the ticket lifecycle (WAITING → CALLED → SERVING → DONE), and the call-next/serve/done actions.'},
        {'name': 'visits', 'description': 'Patient visits — register a visit, snapshot a pathway template into VisitSteps, and move each step through start/complete/skip.'},
        {'name': 'health', 'description': 'Liveness probe.'},
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

CORS_ALLOWED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
]

# The browser only ever talks to the Next.js origin (it proxies /api/* to us
# server-side, see frontend/next.config.ts) but that proxy does not
# necessarily preserve the original Host header, so Django's same-origin
# Referer/Origin check for CSRF can't rely on request.get_host() matching.
# Trusting the frontend origin explicitly keeps POST /api/accounts/login
# (and every other mutating endpoint) working through the proxy.
CSRF_TRUSTED_ORIGINS = [
    'http://localhost:3000',
    'http://127.0.0.1:3000',
    'https://khal.tortoise-theropod.ts.net',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
