# Generated by Django 6.1.1 on 2026-09-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('code', models.CharField(max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level_no', models.IntegerField()),
                ('name_th', models.CharField(max_length=80)),
                ('name_en', models.CharField(max_length=80)),
                ('plan_image', models.ImageField(blank=True, null=True, upload_to='floor_plans/')),
                ('plan_scale_m_per_px', models.FloatField(blank=True, null=True)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='facility.building')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_type', models.CharField(choices=[('SERVICE_POINT', 'Service Point'), ('JUNCTION', 'Junction'), ('VERTICAL_CONNECTOR', 'Vertical Connector'), ('KIOSK', 'Kiosk'), ('ENTRANCE', 'Entrance')], max_length=30)),
                ('name_th', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
                ('pos_x', models.FloatField()),
                ('pos_y', models.FloatField()),
                ('vertical_group', models.CharField(blank=True, max_length=80)),
                ('location_qr_code', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('service_point_code', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('department_th', models.CharField(blank=True, max_length=120)),
                ('department_en', models.CharField(blank=True, max_length=120)),
                ('is_active', models.BooleanField(default=True)),
                ('device_code', models.CharField(blank=True, max_length=60, null=True, unique=True)),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='facility.floor')),
            ],
        ),
        migrations.CreateModel(
            name='Edge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_m', models.FloatField()),
                ('edge_type', models.CharField(choices=[('CORRIDOR', 'Corridor'), ('ELEVATOR', 'Elevator'), ('STAIRS', 'Stairs'), ('RAMP', 'Ramp')], max_length=20)),
                ('walk_time_sec', models.IntegerField()),
                ('is_bidirectional', models.BooleanField(default=True)),
                ('wheelchair_accessible', models.BooleanField(default=True)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_from', to='facility.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edges_to', to='facility.node')),
            ],
        ),
    ]
