# Generated by Django 6.1.1 on 2026-09-19 06:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=120)),
                ('name_en', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='PathwayTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_th', models.CharField(max_length=150)),
                ('name_en', models.CharField(max_length=150)),
                ('is_active', models.BooleanField(default=True)),
                ('care_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pathway_templates', to='pathway.carecategory')),
            ],
        ),
        migrations.CreateModel(
            name='TemplateStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence_order', models.PositiveIntegerField()),
                ('pathway_template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='pathway.pathwaytemplate')),
                ('prerequisite_steps', models.ManyToManyField(blank=True, related_name='dependent_steps', to='pathway.templatestep')),
                ('service_point', models.ForeignKey(limit_choices_to={'node_type': 'SERVICE_POINT'}, on_delete=django.db.models.deletion.PROTECT, related_name='template_steps', to='facility.node')),
            ],
            options={
                'ordering': ['sequence_order'],
            },
        ),
    ]
